In [1]:
import numpy as np
import pandas as pd

In [16]:
list1 = [1, None, 3, 4]

values = np.array(list1)

In [37]:
values[values != np.array(None)]

array([1, 3, 4], dtype=object)

In [17]:
values

array([1, None, 3, 4], dtype=object)

In [7]:
values.mean()

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [8]:
for dtype in ['object', 'int']:
    print("dtype=", dtype)
    %timeit np.arange(1E6, dtype=dtype).sum()
    print()

dtype= object
101 ms ± 6.99 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

dtype= int
3.39 ms ± 280 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)



1000000.0

In [18]:
list3 = [1, np.nan, 3, 4]
values2 = np.array(list3)

In [19]:
values2

array([ 1., nan,  3.,  4.])

In [20]:
values2.dtype

dtype('float64')

In [25]:
1 + 3 + 4 + np.nan 

nan

In [29]:
values2.sum()

nan

In [31]:
values2

array([ 1., nan,  3.,  4.])

In [30]:
np.nansum(values2) #ignores the missing values np.nan

8.0

In [32]:
np.nanmin(values2)

1.0

In [35]:
np.nanmax(values2)

4.0

Pandas

In [60]:
pd.Series([5, 6, 67, None])

0     5.0
1     6.0
2    67.0
3     NaN
dtype: float64

In [71]:
x = pd.Series(range(5), dtype=int)

In [72]:
x

0    0.0
1    1.0
2    2.0
3    3.0
4    4.0
dtype: float64

In [52]:
x[1] = None # int -> float ; None -> np.nan

In [59]:
x 

0    0.0
1    NaN
2    2.0
3    3.0
4    4.0
dtype: float64

In [62]:
x

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [69]:
x[3] = None

In [70]:
x

0    0.0
1    1.0
2    2.0
3    NaN
4    4.0
dtype: float64

In [57]:
xnp = np.array([0, None, 2, 3, 4])

In [58]:
xnp

array([0, None, 2, 3, 4], dtype=object)

In [77]:
xfloat = pd.Series(range(5), dtype=float)

In [78]:
xfloat

0    0.0
1    1.0
2    2.0
3    3.0
4    4.0
dtype: float64

In [79]:
xfloat[2] = None

In [80]:
xfloat

0    0.0
1    1.0
2    NaN
3    3.0
4    4.0
dtype: float64

In [82]:
xobj = pd.Series(range(5), dtype=object)

In [83]:
xobj

0    0
1    1
2    2
3    3
4    4
dtype: object

In [86]:
xobj[3] = np.nan

In [87]:
xobj

0      0
1      1
2      2
3    NaN
4      4
dtype: object

In [133]:
xbool = pd.Series([1, 0, 3, 4, 0, 0, 2, 2], dtype=bool)

In [134]:
xbool

0     True
1    False
2     True
3     True
4    False
5    False
6     True
7     True
dtype: bool

In [135]:
xbool[3] = None

In [136]:
xbool

0     True
1    False
2     True
3    False
4    False
5    False
6     True
7     True
dtype: bool

### Detecting missing values

In [177]:
data = pd.Series([1, np.nan, 'hello', None])

In [178]:
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [179]:
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [146]:
# isnull --> True if value is missing else false

In [147]:
data.notnull()

0     True
1    False
2     True
3    False
dtype: bool

In [148]:
~data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

In [167]:
databool = pd.Series([1, 0, 3, 4, 0, 0, 2], dtype=bool)

In [168]:
databool

0     True
1    False
2     True
3     True
4    False
5    False
6     True
dtype: bool

In [169]:
databool[2] = np.nan

In [170]:
databool

0    1.0
1    0.0
2    NaN
3    1.0
4    0.0
5    0.0
6    1.0
dtype: float64

In [171]:
databool.isnull()

0    False
1    False
2     True
3    False
4    False
5    False
6    False
dtype: bool

In [174]:
pd.Series([1, 2, 3, 4, np.nan, None], dtype='object').isnull() #null includes both np.nan and None 

0    False
1    False
2    False
3    False
4     True
5    False
dtype: bool

In [175]:
type(None)

NoneType

In [176]:
type('None')

str

In [180]:
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [181]:
data.dropna()

0        1
2    hello
dtype: object

In [197]:
df = pd.DataFrame([[1, np.nan, 2],
                  [2, 3, 5], 
                  [np.nan, 4, 5]])

In [187]:
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  5

In [186]:
df.dropna() #rows

0    1  2
1  2.0  3.0  5

In [189]:
df.dropna(axis='columns') #columns 

2
0  2
1  5
2  5

In [191]:
df.dropna(how='all', axis='rows') #by default how='any' and axis='rows'

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  5

In [192]:
df.loc[3, :] = [np.nan, np.nan, np.nan]

In [195]:
df

0    1    2
0  1.0  NaN  2.0
1  2.0  3.0  5.0
2  NaN  4.0  5.0
3  NaN  NaN  NaN

In [194]:
df.dropna(how='all', axis='rows')

0    1    2
0  1.0  NaN  2.0
1  2.0  3.0  5.0
2  NaN  4.0  5.0

In [196]:
df.dropna(how='any', axis='rows')

0    1    2
1  2.0  3.0  5.0

In [198]:
df = pd.DataFrame([[1, np.nan, 2],
                  [2, 3, 5], 
                  [np.nan, 4, 5]])

In [199]:
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  5

In [200]:
df.loc[:, 3] = [np.nan, np.nan, np.nan]

In [201]:
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  5 NaN

In [202]:
df.dropna(how='any', axis='columns')

2
0  2
1  5
2  5

In [203]:
df.dropna(how='all', axis='columns')

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  5

In [204]:
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  5 NaN

In [205]:
df.dropna(axis='rows', thresh=4) #atleast 4 non-null values

Empty DataFrame
Columns: [0, 1, 2, 3]
Index: []

In [206]:
df.dropna(axis='rows', thresh=3) #atleast 3 non-null values

0    1  2   3
1  2.0  3.0  5 NaN

In [207]:
df.dropna(axis='rows', thresh=2) #atleast 2 non-null values

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  5 NaN