In [1]:
import numpy as np

In [7]:
x = np.array([[1, 4, 3, 7], [6, 2, 8, 9], [5, 1, 6, 2]])

In [8]:
x.shape

(3, 4)

In [12]:
x.ravel() #method

array([1, 4, 3, 7, 6, 2, 8, 9, 5, 1, 6, 2])

Numpy ravel

In [11]:
np.ravel(x) #function

(12,)

In [20]:
b = np.array([[[ 0,  2,  4],
        [ 1,  3,  5]],
       [[ 6,  8, 0],
        [ 7,  9, 11]]])

In [21]:
#b.shape?
b.shape

(2, 2, 3)

In [22]:
b.ravel()

array([ 0,  2,  4,  1,  3,  5,  6,  8,  0,  7,  9, 11])

Question. 

In [24]:
a = np.array([[1, 2, 3], [3, 4, 5]])
a.shape

(2, 3)

In [26]:
b = np.ravel(a)
print(b[0])

1


Numpy reshape

In [27]:
arr = np.array([[1, 4, 3, 7], [6, 2, 8, 9], [5, 1, 6, 2]])

In [28]:
arr.reshape(6,2)

array([[1, 4],
       [3, 7],
       [6, 2],
       [8, 9],
       [5, 1],
       [6, 2]])

In [31]:
arr.reshape(-1, 2)

array([[1, 4],
       [3, 7],
       [6, 2],
       [8, 9],
       [5, 1],
       [6, 2]])

In [38]:
arr.reshape(6, -1)

array([[1, 4],
       [3, 7],
       [6, 2],
       [8, 9],
       [5, 1],
       [6, 2]])

In [33]:
arr.reshape(2, 6)

array([[1, 4, 3, 7, 6, 2],
       [8, 9, 5, 1, 6, 2]])

In [49]:
arr1 = np.array([[1, 4], [6, 2], [5, 1]])
arr2 = np.array([[1, 2, 3], [3, 4, 4]])
arr1.shape

(3, 2)

In [50]:
arr2.shape

(2, 3)

In [54]:
arr2 = arr2.reshape(3, 2)

In [55]:
np.hstack((arr1, arr2))

array([[1, 4, 1, 2],
       [6, 2, 3, 3],
       [5, 1, 4, 4]])

In [35]:
arr.reshape(2, -2)

array([[1, 4, 3, 7, 6, 2],
       [8, 9, 5, 1, 6, 2]])

In [59]:
x = np.array([1, 2, 3])
y = np.array([2, 4])
x * y

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [62]:
x = np.array([1, 2, 3, 4, 5]) # 5 elements 
y = 2 # 1 element 
x * y # 5 elements 

array([ 2,  4,  6,  8, 10])

In [61]:
x = np.array([[0, 0, 0], [10, 10, 10], [20, 20, 20], [30, 30, 30]])
y = np.array([0, 1, 2])
x + y

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [ ]:
x = np.array([[0, 0, 0], [10, 10, 10], [20, 20, 20], [30, 30, 30]])
y = np.array([0, 1, 2, 3])
x + y

# Perform Operations on Arrays

Performing mathematical operations on arrays is extremely simple. Let's see some common operations.


#### Basic Mathematical Operations

NumPy provides almost all the basic math functions - exp, sin, cos, log, sqrt etc. The function is applied to each element of the array.

#### Basic Linear Algebra Operations

NumPy provides the ```np.linalg``` package to apply common linear algebra operations, such as:
* ```np.linalg.inv```: Inverse of a matrix
* ```np.linalg.det```: Determinant of a matrix
* ```np.linalg.eig```: Eigenvalues and eigenvectors of a matrix
    
Also, you can multiple matrices using ```np.dot(a, b)```. 

In [75]:
# Basic mathematical operations
a = np.arange(1, 20)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [76]:
# sin, cos, exp, log
print(np.sin(a))
print(np.cos(a))
print(np.exp(a))
print(np.log(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849 -0.54402111 -0.99999021 -0.53657292
  0.42016704  0.99060736  0.65028784 -0.28790332 -0.96139749 -0.75098725
  0.14987721]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026 -0.83907153  0.0044257   0.84385396
  0.90744678  0.13673722 -0.75968791 -0.95765948 -0.27516334  0.66031671
  0.98870462]
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04 5.98741417e+04 1.62754791e+05
 4.42413392e+05 1.20260428e+06 3.26901737e+06 8.88611052e+06
 2.41549528e+07 6.56599691e+07 1.78482301e+08]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509 2.39789527 2.48490665
 2.56494936 2.63905733 2.7080502  2.77258872 2.83321334 2.89037176
 2.94443898]


Question.

In [77]:
np.sin(np.pi / 2.0)

1.0

In [79]:
arr_sin = np.array((0.0, 30.0, 45.0, 60.0, 90.0)) * np.pi / 180.0
arr_sin

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [80]:
np.sin(arr_sin)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

Question. 

In [81]:
arr_cos = np.array([0.0, np.pi/2.0, np.pi])

In [82]:
np.cos(arr_cos)

array([ 1.000000e+00,  6.123234e-17, -1.000000e+00])

Question.

In [83]:
np.exp(0.0)

1.0

In [84]:
np.exp(1.0)

2.718281828459045

In [89]:
np.exp([2, 3, 4, 5])

array([  7.3890561 ,  20.08553692,  54.59815003, 148.4131591 ])

In [ ]:
5**x

Question. 

In [ ]:
#np.exp2 calculates 2**p for all p in the input array.

In [86]:
np.exp2(1.0)

2.0

In [87]:
np.exp2(0.0)

1.0

In [88]:
np.exp2(np.arange(5))

array([ 1.,  2.,  4.,  8., 16.])

### Linear Algebra operations using np.linalg

In [90]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[2, 3], [4, 5]])
#element wise multiplication
a * b

array([[ 2,  6],
       [12, 20]])

In [91]:
#matrix multiplication
a @ b

array([[10, 13],
       [22, 29]])

In [92]:
np.dot(a, b)

array([[10, 13],
       [22, 29]])

In [93]:
np.matmul(a, b)

array([[10, 13],
       [22, 29]])

Question. Determinant of a matrix

In [94]:
np.linalg.det(a)

-2.0000000000000004

In [ ]:
# we can compute determinant of a stack of matrices
a1 = np.array([ [[1, 2], [3, 4]], [[1, 2], [2, 1]], [[1, 3], [3, 1]] ])


In [ ]:
np.linalg.det(a1)

Question. Inverse of a matrix

In [95]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

### numpy.vectorize 

#### Apply User Defined Functions

You can also apply your own functions on arrays. For e.g. applying the function ```x/(x+1)``` to each element of an array.

One way to do that is by looping through the array, which is the non-numpy way. You would rather want to write **vectorised code**. 

The simplest way to do that is to vectorise the function you want, and then apply it on the array. Numpy provides the ```np.vectorize()``` method to vectorise functions.

In [96]:
a = np.arange(20)

In [97]:
# The non-numpy way, not recommended
a_list = [x/(x+1) for x in a]
print(a_list)

[0.0, 0.5, 0.6666666666666666, 0.75, 0.8, 0.8333333333333334, 0.8571428571428571, 0.875, 0.8888888888888888, 0.9, 0.9090909090909091, 0.9166666666666666, 0.9230769230769231, 0.9285714285714286, 0.9333333333333333, 0.9375, 0.9411764705882353, 0.9444444444444444, 0.9473684210526315, 0.95]


In [98]:
# The numpy way: vectorize the function, then apply it
f = np.vectorize(lambda x: x/(x+1))
f(a)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ,
       0.83333333, 0.85714286, 0.875     , 0.88888889, 0.9       ,
       0.90909091, 0.91666667, 0.92307692, 0.92857143, 0.93333333,
       0.9375    , 0.94117647, 0.94444444, 0.94736842, 0.95      ])

In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

In [ ]:
a = [[1,2,3,4], [5,6,7,8], [9,10,11,12]]
b = a[:2][1:3]

In [ ]:
b[0][0] = 77
print(a[0][1])

In [6]:
a = np.array([[1, 2, 3], [1, 0, 4]])
a.shape

(2, 3)

In [70]:
ary = np.array([1, 2, 3, 5, 8])

In [71]:
ary = ary + 1
print(ary)

[2 3 4 6 9]


In [67]:
a = np.array([1, 2, 3, 4, 5])
b = np.arange(0, 10, 2)
c = a + b
print(c[4])

13


In [72]:
b 

array([0, 2, 4, 6, 8])

In [73]:
a 

array([1, 2, 3, 4, 5])

In [74]:
c

array([ 1,  4,  7, 10, 13])