In [43]:
list1 = [1, 2, 3, 4]
import random

In [46]:
random.shuffleList(list1)
#list1

AttributeError: module 'random' has no attribute 'shuffleList'

In [ ]:
#some_list = list() yes
#some_list = list([1, 2, 3]) yes
#some_list = [1, 2, 3] yes
#some_list = list(1, 2, 3) no
#print(some_list)

In [ ]:
#new_list = [expression for element in iterable if condition]
#new_list = [expression if condition else expression_2 for element in iterable]

In [11]:
v = ('a','e','i','o','u','A','E','I','O','U')
input_list=['wood', 'old', 'apple', 'big', 'item', 'euphoria']
list_vowel =[i for i in input_list if i.startswith(v)]
list_vowel

['old', 'apple', 'item', 'euphoria']

Question. Find squares of the list A = [1, 2, 3, 4]

In [2]:
A = [1, 2, 3, 4]
result = []

#for loop
for element in A:
    result.append(element**2)
print(result)

#list comprehensions
result = [element**2 for element in A]
print(result)

[1, 4, 9, 16]
[1, 4, 9, 16]


Question. Find common numbers from two lists A = [1, 2, 3, 4], B = [4, 2, 6, 9]

In [8]:
A = [1, 2, 3, 4]
B = [4, 2, 6, 9]

result = []
for a in A:
    for b in B:
        if a == b:
            result.append(a)
#print(result)
        

result = [a for a in A for b in B if a==b]
print(result)

[2, 4]


Question. You are given an integer 'n' as the input. Create a list comprehension containing the squares of the integers from 1 till n^2 (including 1 and n), and print the list. For example, if the input is 4, the output should be a list as follows: [1, 4, 9, 16]

Question. Suppose we need to create a list of multiple of 6 for just even numbers between 1 to 10.

In [3]:
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[2, 4, 6, 8, 10]
[12, 24, 36, 48, 60]

result = [number*6 for number in range(1, 11) if number%2==0]
print(result)

[12, 24, 36, 48, 60]


Question. Suppose we need to create a list of multiple of 6 for even numbers between 1 to 10 and multiple of 5 for rest of the numbers.

In [4]:
result = [number*6 if number%2==0 else number*5 for number in range(1, 11)]
print(result)

[5, 12, 15, 24, 25, 36, 35, 48, 45, 60]


In [ ]:
import math 
import random

In [12]:
#import the numpy library
import numpy as np

In [15]:
#create a 1 dimensional array
array_1d = np.array([2, 4, 5, 6, 7, 9])
array_1d
#print(type(array_1d))

array([2, 4, 5, 6, 7, 9])

In [16]:
# Creating a 2-D array using two lists
array_2d = np.array([[2, 3, 4], [5, 8, 7]])
array_2d

array([[2, 3, 4],
       [5, 8, 7]])

### Creating Numpy arrays

#### List / Tuple to numpy array

In [17]:
#create an array from list
array_from_list = np.array([1, 2, 3, 4])
array_from_list

array([1, 2, 3, 4])

In [18]:
# create an array from a tuple
array_from_tuple = np.array((2, 2, 3, 4))
array_from_tuple

array([2, 2, 3, 4])

#### Numpy array of fixed size 

In [22]:
# Creating a 2 x 4 array of ones
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
# By default, numpy creates array with data type float
np.ones((2, 4), dtype = np.int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [25]:
#create an array of zeros
np.zeros((2, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
# Array of random numbers in the half open interval [0.0, 1.0)
np.random.random((3, 4))

array([[0.10673071, 0.80701028, 0.03443213, 0.58123379],
       [0.24814887, 0.28892508, 0.53127111, 0.41245267],
       [0.0687875 , 0.54224188, 0.43524921, 0.74942575]])

In [29]:
# np.arange() is the numpy equivalent of range()
# Values are generated within the half-open interval [start, stop) separated by step 
np.arange(start = 10, stop = 20, step = 2)

array([10, 12, 14, 16, 18])

In [32]:
help(np.linspace)

Help on function linspace in module numpy.core.function_base:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    Parameters
    ----------
    start : scalar
        The starting value of the sequence.
    stop : scalar
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is the last sample. Otherwise, it is not included.
        Default is True.
    retstep : bo

In [33]:
#np.linspace()
#Sometimes, you know the length of the array, not the step size
#Returns num evenly spaced samples, calculated over the interval [start, stop].

np.linspace(2, 3, num = 5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

#### Question. Your task is to print a reversed NumPy array with the element type float. 

In [35]:
arr1 = [1, 2, 3, 4]
#write code below
print(np.array(arr1[::-1], dtype=float))

[4. 3. 2. 1.]


#### Other ways of creating Numpy arrays

In [87]:
# np.full()
# takes 2 arguments -- shape and fill value
np.full((2, 3), 12)

array([[12, 12, 12],
       [12, 12, 12]])

In [102]:
#np.tile()
# takes 2 arguments -- array and repetitions
a = np.array([[0, 1], [2, 3]])
#a.shape
#a = np.array([
 #   [0, 1, 2]
#])
#a = [
    #[0, 1, 2, 0, 1, 2],
    #[0, 1, 2, 0, 1, 2],
    #[0, 1, 2, 0, 1, 2]
#]
#a.shape
np.tile(a, reps = 2) #length of reps => d = 2

array([[0, 1, 0, 1],
       [2, 3, 2, 3]])

In [105]:
#np.eye() N * M matrix 
np.eye(3, 2, dtype=int) # n = 3, m = 2 

array([[1, 0],
       [0, 1],
       [0, 0]])

In [113]:
#np.random.randint(low, high= None, size = None)
# integers in the interval [low, high)
np.random.randint(5, size = (2, 5)) # [0, 5)

array([[2, 2, 2, 3, 3],
       [3, 0, 1, 0, 1]])

### Structure and content of Numpy arrays 

In [65]:
#ndarray.shape
x = np.zeros((3, 4, 5), dtype=np.int)
x.shape 

(3, 4, 5)

In [64]:
y = [
    [[1, 2, 3],
     [2, 3, 4]],
    
    [[1, 2, 3],
     [2, 3, 4]]
]
y_np = np.array(y)
y_np.shape
y_np

array([[[1, 2, 3],
        [2, 3, 4]],

       [[1, 2, 3],
        [2, 3, 4]]])

In [66]:
#ndarray.dtype
x.dtype

dtype('int64')

In [68]:
#ndarray.ndim
arr1 = np.array([1, 2, 3])
arr1.ndim

1

In [69]:
#ndarray.itemsize
x.itemsize

8

In [72]:
x

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

In [71]:
#ndarray.size

x.size

60

In [85]:
x1 = np.array([1, 2, 3, 4])
x1.transpose().shape
x1.shape

(4,)

In [81]:
arr2.transpose()

array([[1, 3],
       [2, 4]])

In [78]:
#ndarray.T
arr2 = np.array([[1, 2], [3, 4]])

arr2.

array([[1, 3],
       [2, 4]])

In [79]:
arr2

array([[1, 2],
       [3, 4]])

In [77]:
y_np.shape

(2, 2, 3)

### Comparing the computation time of Python lists and Numpy arrays

In [114]:
## Comparing time taken for computation
list_1 = [i for i in range(1000000)]
list_2 = [j**2 for j in range(1000000)]

# list multiplication
import time

# store start time, time after computation, and take the difference
t0 = time.time()
product_list = list(map(lambda x, y: x*y, list_1, list_2))
t1 = time.time()
list_time = t1 - t0 
print(t1-t0)


# numpy array 
array_1 = np.array(list_1)
array_2 = np.array(list_2)

t0 = time.time()
array_3 = array_1*array_2
t1 = time.time()
numpy_time = t1 - t0

print(t1-t0)

print("The ratio of time taken is {}".format(list_time/numpy_time))

0.27524805068969727
0.007869958877563477
The ratio of time taken is 34.974522100033326
