In [1]:
import numpy as np
import pandas as pd

In [33]:
arr = np.arange(9).reshape(3, 3)

In [34]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
arr[[2, 1]]

array([[6, 7, 8],
       [3, 4, 5]])

Question 1. Swap columns indexed 0, 1

In [5]:
arr = arr[:, [1, 0, 2]]

In [6]:
arr

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [9]:
arr[:, [0, 1]] = arr[:, [1, 0]]

In [10]:
arr

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [13]:
temp = np.copy(arr[:, 0])
arr[:, 0] = arr[:, 1]
arr[:, 1] = temp

In [14]:
arr

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [17]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
arr.T[[0,1]] = arr.T[[1,0]]

In [19]:
arr

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

Question 2. Swap rows indexed 1 and 2. 

In [22]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
arr[[0, 2, 1], :] #1

array([[0, 1, 2],
       [6, 7, 8],
       [3, 4, 5]])

In [24]:
arr[[1, 2]] = arr[[2, 1]] #2

In [25]:
arr

array([[0, 1, 2],
       [6, 7, 8],
       [3, 4, 5]])

In [30]:
arr[[1,2],:] = arr[[2,1],:] #3

In [31]:
arr

array([[0, 1, 2],
       [6, 7, 8],
       [3, 4, 5]])

Question 3. What will be the output?

In [37]:
x = np.array([[1, 2], [3, 4], [5, 6]])
y = x[[0, 1, 2], [0, 1, 0]]

In [38]:
# a. array([[1, 2, 1], [3, 4, 5], [5, 6, 5]])
# b. array([[0, 1, 2], [0, 3, 4], [0, 5, 6]])
# c. array([1, 4, 5])

In [39]:
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
x[[0, 1, 2], [0, 1, 0]]

In [40]:
y

array([1, 4, 5])

Question 4. Output all the elements greater than 5 in the array

In [41]:
x = np.arange(12).reshape(4, 3)

In [42]:
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [43]:
x.shape

(4, 3)

In [46]:
x[x>5] #1

array([ 6,  7,  8,  9, 10, 11])

In [47]:
x[x[:,:]>5] #2

array([ 6,  7,  8,  9, 10, 11])

Question 5. Write a program to output sum of both diagonals in the matrix given below

In [49]:
x = np.arange(9).reshape(3, 3)

In [50]:
x # x[0][2], x[1][1], x[2][0]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [52]:
#1
sum1 = 0 # n x n matrix 
for i in range(0, 3):
    sum1 += x[i, i] + x[2-i, 2-i]

In [57]:
n = 3

In [58]:
sum([x[i][i]+x[i][n-i-1] for i in range(n)]) 

24

In [64]:
x.diagonal(0) #3
y = x[:,::-1]
y.diagonal()
z = x.diagonal(0) + y.diagonal(0)
z.sum()

24

In [68]:
def Sums(mat, n=3):

    first = 0
    second = 0;

    for i in range(0, n):
        for j in range(0, n):
            if (i == j):
                first += mat[i][j]


            if ((i + j) == n-1):
                second += mat[i][j]

    return first+second

In [69]:
Sums(x)

24

In [72]:
x1=np.diag(x)
x1.sum()
x2=x[:,::-1]  
x3=np.diag(x2)
x3.sum()
x1.sum() + x3.sum()

24

In [73]:
y = x[:,::-1]
print(np.trace(x)+y.diagonal().sum())

24


In [74]:
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
       'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
       'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1], 
       'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

In [75]:
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

Question 6. Create a DataFrame df from the dictionary data which has the list labels as index. 

In [129]:
df = pd.DataFrame(data, index=labels)

In [92]:
df

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

Question 7. Display a summary of the basic information about this DataFrame and its data.

In [79]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
animal      10 non-null object
age         8 non-null float64
visits      10 non-null int64
priority    10 non-null object
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes


In [80]:
df.describe()

age     visits
count  8.000000  10.000000
mean   3.437500   1.900000
std    2.007797   0.875595
min    0.500000   1.000000
25%    2.375000   1.000000
50%    3.000000   2.000000
75%    4.625000   2.750000
max    7.000000   3.000000

Question 8. Return the first 3 rows of this df.

In [81]:
df.head(3)

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

In [82]:
df.iloc[:3]

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

In [83]:
df[:3]

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

Question 8. Add a new row 'k' to the above df . 
The values of a cat aged 5.5 years, 2 visits and no priority.

In [84]:
df

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

In [103]:
df.loc['k'] = ['cat', 5.5, 2, 'no']

In [104]:
df

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no
k    cat  5.5       2       no

In [96]:
df2 = pd.DataFrame({'animal' : 'cat' , 'age' : 5.5, 'visits':2,'priority':'no'}, index=['k']) 
df.append(df2)

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no
k    cat  5.5       2       no

Question 9. Remove the new row that you added. 

In [108]:
df.drop(index=['k'])

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

In [109]:
help(pd.DataFrame.drop)

Help on function drop in module pandas.core.frame:

drop(self, labels=None, axis=0, index=None, columns=None, level=None, inplace=False, errors='raise')
    Drop specified labels from rows or columns.
    
    Remove rows or columns by specifying label names and corresponding
    axis, or by specifying directly index or column names. When using a
    multi-index, labels on different levels can be removed by specifying
    the level.
    
    Parameters
    ----------
    labels : single label or list-like
        Index or column labels to drop.
    axis : {0 or 'index', 1 or 'columns'}, default 0
        Whether to drop labels from the index (0 or 'index') or
        columns (1 or 'columns').
    index, columns : single label or list-like
        Alternative to specifying axis (``labels, axis=1``
        is equivalent to ``columns=labels``).
    
        .. versionadded:: 0.21.0
    level : int or level name, optional
        For MultiIndex, level from which the labels will be removed.

Question 9. Select the rows where the cat is aged less than 3. 

In [110]:
df

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no
k    cat  5.5       2       no

In [115]:
df.loc[(df['animal'] == 'cat') & (df['age'] < 3)]

animal  age  visits priority
a    cat  2.5       1      yes
f    cat  2.0       3       no

Question 10. In the animal column . change the 'snake' entries to 'cobra'. 


In [113]:
df

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no
k    cat  5.5       2       no

In [126]:
df.loc[df['animal'] == 'snake',['animal']] = 'cobra'

In [119]:
df

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

In [133]:
df.replace({'animal': 'snake'}, {'animal': 'cobra'})

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  cobra  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  cobra  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

In [121]:
df

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

In [130]:
for animal in df:
    for name in animal: 
        if name == 'snake':
            name = 'cobra'

In [131]:
df

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

Question 11. Select just the 'animal' and 'age' from the dataframe df

In [137]:
df.loc[:, :'age']

animal  age
a    cat  2.5
b    cat  3.0
c  cobra  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  cobra  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

Question 12. Select the data in rows [3, 4, 8] and in columns ['animal', 'age']

In [139]:
df.iloc[[3, 4, 8], [0, 1]]

animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0

In [140]:
df.iloc[[3, 4, 8], :2]

animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0

In [141]:
df.loc[df.index[[3, 4, 8]], ['animal', 'age']]

animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0

In [142]:
df.loc[['d', 'e', 'i'], ['animal', 'age']]

animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0

In [143]:
df.loc[df.iloc[[3,4,8],:].index,['animal','age']]

animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0

Question 13. Select only the rows where the number of visits is greater than and equal to 3. 

In [144]:
df

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  cobra  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  cobra  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

In [146]:
df[df['visits']>=3]

animal  age  visits priority
b    cat  3.0       3      yes
d    dog  NaN       3      yes
f    cat  2.0       3       no

Question 14. Select the rows where the age is missing i.e it is NaN

In [147]:
df

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  cobra  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  cobra  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

In [148]:
df[df['age'].isnull()]

animal  age  visits priority
d    dog  NaN       3      yes
h    cat  NaN       1      yes