In [1]:
import numpy as np

In [65]:
country = {}
def addone(c):
    if c in country:
        country[c] += 1
    else:
        country[c] = 1
addone('China')
addone('Japan')
addone('china')

In [67]:
len(country) #len of dict is number of key value pairs

3

In [2]:
# Indexing and slicing one dimensional arrays
array_1d = np.arange(10) # [start, stop) step as mentioned
print(array_1d)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
# Third element
array_1d[2]

2

In [10]:
# Specific elements [2, 5, 6]
# Notice that array[2, 5, 6] will throw an error, you need to provide the indices as a list
array_1d[[2, 5, 6]]

In [9]:
# Slice third element onwards
array_1d[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# Slice first three elements
array_1d[:3]

array([0, 1, 2])

In [12]:
# Slice third to seventh elements
array_1d[2:7]

array([2, 3, 4, 5, 6])

In [13]:
# Subset starting 0 at increment of 2 
array_1d[::2]

array([0, 2, 4, 6, 8])

In [14]:
#iterations are also similar to lists -- print squares of each element
for i in array_1d:
    print(i**2)

0
1
4
9
16
25
36
49
64
81


In [15]:
array_1d ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

Question. 

In [19]:
arr = np.arange(10)
b = arr[2:7:2]
arr[2:7:2]

array([2, 4, 6])

In [17]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Multidimensional arrays

In [21]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d.shape
print(arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
#for a 2d array -- elements are no longer scalars. rather, they are 1d arrays.
arr2d[2]

array([7, 8, 9])

In [23]:
# individual elements can be accessed recursively. but it's a lot of work
arr2d[0][2]

3

In [25]:
# pass a comma separated list of indices to select individual elements.
arr2d[1, 1]

5

In [27]:
array_2d = np.array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [28]:
array_2d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [29]:
array_2d[1:]

array([[ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [31]:
# Creating a 2-D array
arr_2d = np.array([[2, 5, 7, 5], [4, 6, 8, 10], [10, 12, 15, 19]])
arr_2d

array([[ 2,  5,  7,  5],
       [ 4,  6,  8, 10],
       [10, 12, 15, 19]])

In [32]:
# Third row second column
arr_2d[2, 1]

12

In [39]:
# Slicing the second row, and last three columns
# Notice that the resultant is itself a 1-D array
arr_2d[1, -3:]

array([ 6,  8, 10])

In [40]:
# Slicing all rows and the third column
arr_2d[:,2]

array([ 7,  8, 15])

In [43]:
# Slicing all rows and the first three columns
arr_2d[:, 1:3]

array([[ 5,  7],
       [ 6,  8],
       [12, 15]])

Question. 

In [44]:
a = np.array([[1, 2, 3], [3, 4, 5], [4, 5, 6]])
a

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [ ]:
#output the following 
# array([[2, 3],[4, 5],[5, 6]])

In [45]:
a[:, 1:]

array([[2, 3],
       [4, 5],
       [5, 6]])

Question. 

In [46]:
ar = np.array(["hello", "apple", "mango", "orange"])
#return as output 'pple'

In [52]:
ar[1][1:]

'pple'

Question.

In [53]:
b = np.arange(1, 10)
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
b[-5:-2]

array([5, 6, 7])

In [68]:
arr1 = np.array([[1, 2, 3], [2, 3, 4], [4, 5, 6]])

In [71]:
arr1

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [69]:
arr1.shape

(3, 3)

In [84]:
arr1[2:, :].ndim

2

Question. 

In [59]:
x = np.array([1, -1, -2, 3])
#x_list = [1, -1, -2, 3] #add 20 to each negative element  O(nlogn) > O(n)

In [60]:
x[x < 0] += 20

In [61]:
x

array([ 1, 19, 18,  3])

Question. 

In [ ]:
x = np.array([[0, 1], [1, 1], [2, 2]])

In [ ]:
rowsum = x.sum(1)

In [ ]:
rowsum

Question.

Ellipsis can also be used along with basic slicing. Ellipsis (…) is the number of : objects needed to make a selection tuple of the same length as the dimensions of the array.

In [89]:
# A 3 dimensional array. 
b = np.array([[[1, 2, 3],[4, 5, 6]], 
              [[7, 8, 9],[10, 11, 12]]]) 
b[..., 1]
#print(b[...,1]) #Equivalent to b[: ,: ,1] 

array([[ 2,  5],
       [ 8, 11]])

#### 3-D arrays

In [90]:
array_3d = np.array( [[[0, 1, 2],
                    [3, 4, 5]],
                   
                      [[6, 7, 8],
                    [9, 10, 11]],
                   
    [[12, 13, 14],
    [15, 16, 17]]]
)

In [93]:
array_3d

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]]])

In [94]:
#How will you extract the element 13
array_3d[2, 0, 1]

13

In [100]:
#How will you extract all the elements less than 10
array_3d[array_3d < 10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
#Check if the number is even and convert the array into Boolean 
array_3d = array_3d % 2 == 0 

In [102]:
array_3d

array([[[ True, False,  True],
        [False,  True, False]],

       [[ True, False,  True],
        [False,  True, False]],

       [[ True, False,  True],
        [False,  True, False]]])

Question. 

In [103]:
data = np.random.randint(1, 10, size = (7, 4))

In [104]:
data

array([[3, 5, 3, 9],
       [9, 1, 5, 2],
       [8, 8, 9, 3],
       [5, 9, 2, 5],
       [4, 1, 5, 7],
       [1, 5, 1, 6],
       [1, 4, 5, 1]])

In [106]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [107]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [110]:
data[names == 'Bob']

array([[3, 5, 3, 9],
       [5, 9, 2, 5]])

In [111]:
data[names == 'Bob', 2:]

array([[3, 9],
       [2, 5]])

In [112]:
data[names == 'Bob', 3]

array([9, 5])

In [113]:
#Select the rows in data corresponding to everything but Bob in Names
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [114]:
data[names != 'Bob']

array([[9, 1, 5, 2],
       [8, 8, 9, 3],
       [4, 1, 5, 7],
       [1, 5, 1, 6],
       [1, 4, 5, 1]])

In [116]:
foo = {1: '1', 2:'2', 3:'3'}
del foo[1] #1 is the key

In [117]:
foo

{2: '2', 3: '3'}

In [118]:
foo[1] = '10'

In [119]:
foo

{2: '2', 3: '3', 1: '10'}

In [120]:
del foo[2]

In [121]:
foo

{3: '3', 1: '10'}

In [122]:
len(foo)

2